#include <iostream>
using namespace std;

bool isPalindrome(int num) {
    int original = num;  
    int revNum = 0;

    while (num > 0) {
        int lastdigit = num % 10;
        revNum = revNum * 10 + lastdigit;
        num = num / 10;
    }

    return original == revNum;
}

int main() {
    int n;
    cout << "Enter a number: ";
    cin >> n;

    if (isPalindrome(n)) {
        cout << n << " is a palindrome." << endl;
    } else {
        cout << n << " is not a palindrome." << endl;
    }

    return 0;
}